### ISSUE TITLE
Wrong number of items shown in pages

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-recipe#20]
In the IT and DE version of the web component, if I choose a number of items per page smaller than 6, the results shown in the first pages are less than the number chosen or no items are shown.

Navigating in the successive pages the problem disappears.

![Schermata da 2021-06-11 15-23-27](https://user-images.githubusercontent.com/7909989/121713280-f9f30000-cadc-11eb-88c5-934166c4e421.png)

**Comment by Piiit** [comment]
@maximiliannocker Any news on that issue?

**Comment by Piiit** [comment]
Blocks #2

**Comment by maximiliannocker** [comment]
Sorry for the late reply. 
Sometimes we get an empty detail response from the API then the Webcomponent filters out these recipes. 
For example you can see the empty detail with this API call: 
https://tourism.opendatahub.bz.it/v1/Article?pagenumber=1&pagesize=5&articletype=32&articlesubtype=null&idlist=&langfilter=null&sortbyarticledate=null&odhtagfilter=null&active=null&odhactive=true&seed=null&fields=&language=de&updatefrom=null&searchfilter=

**Comment by maximiliannocker** [comment]
Maybe it is because we are using a language filter and for this language there is no text available, then the API returns an empty result

**Comment by Piiit** [comment]
Strange, I get a result with your example above

**Comment by Piiit** [comment]
> Strange, I get a result with your example above

A sorry, I misread your comment... you mean the detail part is empty

**Comment by maximiliannocker** [comment]
Yes we are using the data from the Detail part. If you go to page 2 you can see data inside of some recipes: https://tourism.opendatahub.bz.it/v1/Article?pagenumber=2&pagesize=5&articletype=32&articlesubtype=null&idlist=&langfilter=null&sortbyarticledate=null&odhtagfilter=null&active=null&odhactive=true&seed=null&fields=&language=de&updatefrom=null&searchfilter=

**Comment by Piiit** [comment]
OK, but what do you do then when you show the whole list? There you have the same issue, but it seems to work there... Which call do you make for the full list?

**Comment by maximiliannocker** [comment]
We use 20 items as default and filters out the items with empty content as we do with a smaller page size. With more items it is not immediately visible that some items are missing. For us it is difficult to display the same number of items every time with the paged API if some content is empty.

**Comment by Piiit** [comment]
@RudiThoeni Do you have a suggestion on how to solve this issue? Could we filter against empty details?

**Comment by RudiThoeni** [comment]
Try also setting langfilter to the desired language maybe there is a bug that setting language does not filter out data that foes not contain the requested language.... will look at it after my return

**Comment by Piiit** [comment]
@maximiliannocker @RudiThoeni @danielecanu
OK so we wait for Rudi then and check if everything is running fine on our APIs, if so I write you back and we can finalize this web component. Thx for your patience ...

**Comment by RudiThoeni** [comment]
Hi

The Article Endpoint has two parameters:
language  -- Cuts out all other languages that are not requested from the json response (post processing)
langfilter -- Filters the DB and gets only data which has this language available

I know it is not very intuitive but it is so for compatibility reasons etc...
for now i think the best thing is to add the langfilter in your request
https://tourism.opendatahub.bz.it/v1/Article?pagenumber=1&pagesize=5&articletype=32&langfilter=de&odhactive=true&language=de

Does this solve the issue? 

P.S you dont need to pass the "null" parameters

**Comment by Piiit** [comment]
@maximiliannocker @RudiThoeni Works, thanks
