### ISSUE TITLE
No items shown if indicated more than one ID

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-recipe#21]
If I put more than one ID separated by a comma no results are shown.
![Schermata da 2021-06-11 17-50-30](https://user-images.githubusercontent.com/7909989/121713917-a8974080-cadd-11eb-9afa-cb98d3d81ef0.png)

**Comment by maximiliannocker** [comment]
I think this is a bug in the API. If you try to make the API call with the Swagger Ui and pass two ids you get no results: [https://tourism.opendatahub.bz.it/swagger/index.html#/Article/get_v1_Article]

**Comment by Piiit** [comment]
@RudiThoeni I tested the idlist filter, but it seems to always return an empty result. Do we use it wrong or have we found a bug?
Please enlighten us ;-)

https://tourism.api.opendatahub.bz.it/v1/Article?pagenumber=1&articletype=255&idlist=BCCEEEC0-739A-90F3-F0E8-268816DBAD48

**Comment by RudiThoeni** [comment]
works now, you are now enlighted ;)

**Comment by Piiit** [comment]
@RudiThoeni Thx a lot... aren't you on holiday?

**Comment by Piiit** [comment]
@maximiliannocker It was a bug inside our API, thanks for your investigation
