### ISSUE TITLE
Search does not work on pages > 1

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/webcomp-recipe#23]
Noticed a little bug.
When in the webcomponent i am on page 2, and a search is done, nothing is found

Reason is because also the parameter "pagenumber" is passed to the searchquery....

**Comment by Piiit** [comment]
@maximiliannocker We found this issue, would it be possible to correct it before our meeting?

**Comment by Piiit** [comment]
@sseppi @danielecanu FYI

**Comment by maximiliannocker** [comment]
@Piiit  Yes I will fix it in the afternoon

**Comment by Piiit** [comment]
@RudiThoeni Please test again under https://webcomponents.opendatahub.testingmachine.eu/webcomponent/32c2bef1-a691-4b93-bc41-56ecb88e39f0... is the bug fixed?

**Comment by RudiThoeni** [comment]
yes i see pagenumber 1 is set, when a search is done, works!
