### ISSUE TITLE
Final web-component integration should be possible with only one script tag

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/webcomp-recipe#4]
The final result should be that I can integrate the web-component in a site with only one script tag like:
`<script src="./webcomp-recipe.js"></script>`

But at the moment two script tags are needed:
```
<script src="https://unpkg.com/vue"></script>
<script src="./webcomp-recipe.js"></script>
```

@maximiliannocker

**Comment by Piiit** [comment]
@maximiliannocker I think this is the most important issue to solve, such that we can show it inside the store and thus have feedback from others. Thank you

**Comment by Piiit** [comment]
@maximiliannocker Solved, thx
