### ISSUE TITLE
Assign more categories in WebComponentStore

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/webcomp-recipe#6]
Currently only the recipe category is assigned to this web-component.
More categories should be added.

@maximiliannocker

**Comment by maximiliannocker** [comment]
Which categories should additionally be added? Should other articletypes from the article API be added?

@sseppi @Piiit

**Comment by Piiit** [comment]
@718r3 Could you please elaborate and give some details about this request... thank you

**Comment by dulvui** [comment]
With categories I meant the 'searchTags' tag in wcs-manifest.json file.

**Comment by Piiit** [comment]
@718r3 Thanks for clarification, if it is just that @maximiliannocker  please ignore this request, as I will add those tags when we deploy it on our store

**Comment by Piiit** [comment]
Belongs to #2

**Comment by Piiit** [comment]
@sseppi What search tags do we want to add here?
